config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  #devise_for :users
  
  
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  #devise_for :users
  root to: "projects#index"
  resources :projects
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/projects.rb
class Projects < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 13
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy]
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    #user_signed_in?
    #current_user
   # user_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title class="font-weight-bold">Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body style = "background-color: #0275d8">

  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
    <a class="navbar-brand text-gradient-primary" href="#">York Portfolio</a>

  </button>

  <div class="navbar">
    <ul class="navbar-nav mr-auto">
      
      <%if user_signed_in?%>
        <li class="nav-item active">
          <div class="btn btn-outline-primary ml-3">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, :class => "btn text-light btn-sm" %> 
          </div> 
        </li>
        <li class="nav-item active">
          <div class="btn btn-outline-primary ml-3">
            <%= button_to "Create New Project", new_project_path, method: :get, :class => "btn text-light btn-sm"%>
          </div> 
        </li>
      <% else %>
        <li class="nav-item active">
          <div class="btn btn-outline-primary ml-3">
            <%= button_to "Sign In", new_user_session_path, method: :get, :class => "btn text-light btn-sm" %>
          </div> 
        </li>
      <%end%>
        <li class="nav-item active">
          <div class="btn btn-outline-primary ml-3">
            <%= button_to "Main", projects_path, method: :get, :class => "btn text-light btn-sm" %>
          </div> 
        </li>
  </div>
</nav>


    <!--
    <div class="navbar navbar-dark fixed-top bg-dark d-flex justify-content-between">
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, :style => "background-color: darkgrey; border-radius: 8px"%>
        <%= button_to "Create New Project", new_project_path, method: :get, :style => "background-color: darkgrey; border-radius: 8px"%>
      <% else %>
        <%= button_to "Sign In", new_user_session_path, method: :get, :style => "background-color: darkgrey; border-radius: 8px"%>
      <%end%>
      <%= button_to "Main", projects_path, method: :get, :style => "background-color: darkgrey; border-radius: 8px"%>
    </div>
      
    -->




    <%=yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>

    <%= form.submit%>
    <!--  :button => "submit", :class => "btn btn-outline-dark text-light btn-lg" -->
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/_projects.html.erb
<div class ="jumbotron container">
<div id="<%= dom_id projects %>">
  <p>
    <strong>Title:</strong>
    <%= projects.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= projects.description %>
  </p>

</div>
</div>

app/views/projects/edit.html.erb
<div class="text-center cover-container d-flex h-100 p-3 mx-auto flex-column">
<main role="main" class="inner cover">

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>


  <div class="btn btn-outline-dark ml-3">
    <%= button_to "Show this project", project_path, method: :get, :class => "btn text-light btn-lg" %>
  </div> 
  <!--
                    <div class="btn btn-outline-primary ml-3">
            <%= button_to "Main", projects_path, method: :get, :class => "btn text-light btn-sm" %>
          </div> 
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
  -->

</main>
</div>

app/views/projects/index.html.erb
<div class="text-center cover-container d-flex h-100 p-3 mx-auto flex-column mr-3">
<main role="main" class="inner cover">


<p style="color: white"><%= notice %></p>

<h1>Projects</h1>

<!--      Failed cooler index code
<div id="projects">
  <div class="album py-5 bg-secondary">
    <div class="container">
      <%@projects.each do |project|%>
        <div class = "col-md-4">
          <%render project%>
          <h4 class = "card mb-4 box-shadow"></h4>
          
          <div class="btn btn-outline-primary ml-3">
            <%= button_to "Show this project", project, method: :get, :class => "btn text-light btn-sm" %>
          </div> 
        </div>
      <%end%>
    </div>
  </div>
</div>
-->

<div id="projects">
 <div class="container row border border-dark rounded rounded-3 w-75 py-5 bg-secondary mx-auto flex-row"> 
  <% @projects.each do |project| %>
    <div class="col-md-4 box-shadow">
    <%= render project %>
    <p>
      <div class="btn btn-outline-primary ml-3">
        <%= button_to "Show this project", project, method: :get, :class => "btn text-light btn-sm" %>
      </div> 
    </p>
    </div>
  <% end %>
  </div>
</div>

<!--
<%= button_to "Create New Project", new_project_path, method: :get, :style => "background-color: darkgrey; border-radius: 10px"%>
-->
<!--<%= link_to "New project", new_project_path %> -->
</div>
</main>

app/views/projects/new.html.erb
<div class="text-center cover-container d-flex h-100 p-3 mx-auto flex-column">
<main role="main" class="inner cover">

<h1>New project</h1>

<%= render "form", project: @project %>

<br>


</main>
</div>

app/views/projects/show.html.erb
<div class="text-center cover-container d-flex h-100 p-3 mx-auto flex-column mr-3">
<main role="main" class="inner cover">



<p style="color: white"><%= notice %></p>

<div class ="container py-5 w-50 border border-dark mt-2 bg-secondary">
  <h4 class=" container font-weight-bold justify-content-center"><%= render @project %></h4>




<%if user_signed_in?%>
<div class="container row justify-content-center">
  <div class="btn btn-outline-primary ml-3"><%= button_to "Edit this project", edit_project_path, method: :get, :class => "btn text-light btn-sm" %></div> 
  
  <div class="btn btn-outline-primary ml-3"><%= button_to "Destroy this project", @project, method: :delete, :class => "btn text-light btn-sm"  %></div> 
</div>
</div>
<%end%>

</div>
</main>